# Generated by Django 6.0.3 on 2026-03-04 15:54

import django.db.models.deletion
import stories.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'Link')], default='image', max_length=10)),
                ('media', models.FileField(blank=True, help_text='Upload an image or video', null=True, upload_to='stories/media/', validators=[stories.models.validate_file_extension])),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, null=True)),
                ('link_url', models.TextField(blank=True, help_text='URL for link stories', null=True)),
                ('link_title', models.CharField(blank=True, help_text='Link preview title', max_length=200, null=True)),
                ('link_description', models.TextField(blank=True, help_text='Link preview description', null=True)),
                ('link_thumbnail', models.URLField(blank=True, help_text='Link preview thumbnail', max_length=500, null=True)),
                ('link_source', models.CharField(blank=True, help_text='Source name (e.g., CNN, BBC)', max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('music_info', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'user')},
            },
        ),
    ]
